### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by commixon** [captainhub/captainhub#1]
Image:
======
- [ ] Build stripped down image
- [ ] Configure networking
- [ ] Configure X-11
- [ ] Configure Chromium

Core backend app:
==============
- [ ] List Interfaces
- [ ] Manage Interfaces
- [ ] UP Wireless AP
- [ ] UP Ad-hoc
- [ ] Connect to external network

Core frontend app:
==============
- [ ] Build main UI
